import "../tailwind.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Playground>{children}</Playground>
      </body>
    </html>
  );
}

export function Playground({ children }: { children: React.ReactNode }) {
  return (
    <div className="w-screen h-screen flex flex-row bg-light-50">
      <div
        style={{
          background: "linear-gradient(145deg, rgba(2,0,36,1) 0%, rgba(162,166,156,1) 0%, rgba(184,191,176,1) 10%, rgba(255,255,255,1) 45%, rgba(255,253,250,1) 75%, rgba(228,193,140,1) 90%, rgba(246,154,60,1) 100%);"
        }}
        className="w-full h-full overflow-hidden"
      >
        {children}
      </div>
    </div>
  );
}
