import "../tailwind.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html>
      <body>
        <Playground>{children}</Playground>
      </body>
    </html>
  );
}

export function Playground({ children }: { children: React.ReactNode;}) {
  return (
    <div className="w-screen h-screen flex flex-row ">
      {children}
    </div>
  );
}
